name:                japanese-calendar
version:             0.3.3.0

dependencies:
- base >= 4.7 && < 5
- template-haskell
- time

ghc-options:
- -Wall
- -Werror
- -Widentities
- -Wmissing-export-lists
- -Wmissing-exported-signatures
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - containers
  - parsec
  - transformers

tests:
  japanese-calendar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - japanese-calendar
    - hspec
    - QuickCheck
