name:                japanese-calendar
version:             0.2.0.0

dependencies:
- base >= 4.7 && < 5
- template-haskell
- time

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  dependencies:
  - parsec
  - transformers

tests:
  japanese-calendar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - japanese-calendar
    - hspec
    - QuickCheck
